spring:
  #security:
  #  oauth2:
  #    resourceserver:
  #      jwt:
  #        jwk-set-uri: http://localhost:8080/realms/M2OLIE-AppAuthDev/protocol/openid-connect/certs
  #        issuer-uri: http://localhost:8080/realms/M2OLIE-AppAuthDev
            # prod https://keycloak.tpma-m2olie.de/realms/M2OLIE-AppAuthDev
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/userDataDatabase}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:pR1SmKfeHsU3}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: postgres
server:
  port: 8090
logging:
  level:
    web: debug